### ISSUE TITLE
Adding source code for other programming languages?

### ISSUE THREAD

**Issue by dossan** [mission-peace/interview#11]
First of all, what you are doing with this project is really amazing, and making all this code open-source is really kind of you. Now, as far as I have understood, you have used only Java to implement your algorithms, but it would be nice to provide implementations also for other programming languages, in case someone didn't know Java. I was thinking I could contribute with some Python implementations, but since I have not so much time, I would be a little bit slow doing it alone. I hope you like this idea, and that someone could start contributing to it.

**Comment by mission-peace** [comment]
I like the idea of providing code for Python/C++. But just like you I m barely able to keep Java code up to date. I would love if you want to contribute python solution for corresponding java solution. If you do make a top level folder python and then corresponding package name as in java and then just send me a PR.

**Comment by dossan** [comment]
As I said, I am not sure I will have time to do it. But the proposal remains. You could explain this in the README file, so other people might also help.

**Comment by mission-peace** [comment]
Yea. I would add it in readme once I have at least set up base for python and C++. Probably I will try to find owners who could own up bulk of C++ and python code.
