### ISSUE TITLE
Adding more comments to improve readability and understanding of the code

### ISSUE THREAD

**Issue by dossan** [mission-peace/interview#12]
I have noticed from some source files that you do not comment so much your code. Since, as far as I have understood, this project is mostly for educative purposes, it would be nice to include some comments in the source code or at least at the beginning of the source code that explains the purpose of the program/algorithm.

It would be nice also to include a link to corresponding video where you explain the algorithm.

**Comment by mission-peace** [comment]
Yea. Initially it was just for my personal usage. Then I started making videos and suddenly this repository got popular. I try to add comments at least in all new code and most of the code for which I have videos. I ll sit one day and add video url to all code for which there is a video.

**Comment by npari** [comment]
Nice work! I came here through the videos. Hope to do all the interesting problems in here :) :+1:

**Comment by mission-peace** [comment]
@npari Hopefully this repository will help you.
