### ISSUE TITLE
Compatibility issue with Graph and BellmanFordShortestPath

### ISSUE THREAD

**Issue by jonathanho41** [mission-peace/interview#130]
###  Problem
The Bellman-Ford algorithm doesn't seem to be compatible with the graph implementation. It fails when the graph is undirected.

Since the Bellman-Ford algorithm iterates through all the edges, it has no notion of which vertex is adjacent. It treats the edges as directed and doesn't take into account the edge v->u when the graph is undirected.
 ```
Vertex<Integer> u = edge.getVertex1();
Vertex<Integer> v = edge.getVertex2();
//relax the edge
//if we get better distance to v via u then use this distance
//and set u as parent of v.
if (distance.get(u) + edge.getWeight() < distance.get(v)) {
    distance.put(v, distance.get(u) + edge.getWeight());
    parent.put(v, u);
}
```

I encountered this problem when Dijkstra and Bellman-Ford returned different results for the following [graph](		https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm#/media/File:Dijkstra_Animation.gif
):

```
Graph<Integer> graph = new Graph<>(false);
graph.addEdge(1, 2, 7);
graph.addEdge(1, 3, 9);
graph.addEdge(1, 6, 14);
graph.addEdge(2, 3, 10);
graph.addEdge(2, 4, 15);
graph.addEdge(3, 6, 2);
graph.addEdge(3, 4, 11);
graph.addEdge(4, 5, 6);
graph.addEdge(5, 6, 9);
```

### Solution
Within the addEdge method of Graph.java, the current implementation is: 
```
Edge<T> edge = new Edge<T>(vertex1,vertex2,isDirected,weight);
allEdges.add(edge);
vertex1.addAdjacentVertex(edge, vertex2);
if(!isDirected){
    vertex2.addAdjacentVertex(edge, vertex1);
}
```

A potential fix could be:
```
Edge<T> edge = new Edge<T>(vertex1,vertex2,isDirected,weight);
allEdges.add(edge);
vertex1.addAdjacentVertex(edge, vertex2);
if(!isDirected){
    edge = new Edge<T>(vertex2,vertex1,isDirected,weight);
    allEdges.add(edge);
    vertex2.addAdjacentVertex(edge, vertex1);
}
```

**Comment by mission-peace** [comment]
Bellman ford algorithm is for directed graph.
