### ISSUE TITLE
Optimal Strategy Game Pick from Ends of array Dynamic Programming

### ISSUE THREAD

**Issue by JamesWClark** [mission-peace/interview#14]
From your YouTube video, [Optimal Strategy Game Pick from Ends of array Dynamic Programming](https://www.youtube.com/watch?v=WxpIHvsu1RI)

I came here looking for the source code because you linked to it in the vid, and I believe you haven't actually written an example. I looked under dynamic...

**Comment by mission-peace** [comment]
Are you looking for this code?
https://github.com/mission-peace/interview/blob/master/src/com/interview/dynamic/NPotGold.java

**Comment by JamesWClark** [comment]
Yes - thank you! Case closed - thanks for sharing your knowledge with us.
