### ISSUE TITLE
Exception when trying to insert a large String

### ISSUE THREAD

**Issue by mfazeen** [mission-peace/interview#15]
Hi,

You have done a wonderful job in the implementation. However, when I try to insert a large String (I can provide the test string) It throws the following exception. It never completed inserting the full string.

Exception in thread "main" java.lang.NullPointerException
	at SuffixTree.nextChar(SuffixTree.java:426)
	at SuffixTree.startPhase(SuffixTree.java:322)
	at SuffixTree.build(SuffixTree.java:143)
	at SuffixTree.main(SuffixTree.java:101)

The string I was trying to insert was 63027 in length. However, another large string with a length of 63067 inserted without any errors (I can provide this test string as well). 

However, the second large string failed at your validation function;

Failed at 58 for index 56
Failed validation
false

I was trying to debug it but couldn't track it down. Wanted to bring it to your attention. Thanks.

**Comment by mission-peace** [comment]
I will look at it. I think there is error in validation function. Do you see infinite loop in some reasonable size string which can be debugged? 


     On Sunday, October 25, 2015 1:46 PM, mfazeen <notifications@github.com> wrote:
   

 Hi,You have done a wonderful job in the implementation. However, when I try to insert a large String (I can provide the test string) It throws the following exception. It never completed inserting the full string.Exception in thread "main" java.lang.NullPointerException
 at SuffixTree.nextChar(SuffixTree.java:426)
 at SuffixTree.startPhase(SuffixTree.java:322)
 at SuffixTree.build(SuffixTree.java:143)
 at SuffixTree.main(SuffixTree.java:101)The string i was trying to insert was 63027 in length. However, another large string with a length of 63067 inserted without and error (I can provide this test string as well). However, the second large string failed at your validation function;Failed at 58 for index 56
Failed validation
falseI was trying to debug it but couldn't track it down. Wanted to bring it to your attention. Thanks.—

**Comment by mfazeen** [comment]
Hi,
Thank you for your prompt reply. The NullPointerException is thrown even before it gets to the validation function. It did not load the complete string to the tree.

The exception is generated when the nextChar(int i) function try to access the start value of the activeNode child at the line:

return input[active.activeNode.child[input[active.activeEdge]].start + active.activeLength];

(last return statement in the else block in the nextChar function)

At this line the "active.activeNode.child[input[active.activeEdge]]" is null for sum reason and that failed the tree creation.
I.e. the activeNode child at the input[active.activeEdge] location is null for some reason. I assume that either this child is not created correctly in a previous step or the index of the child is incorrect. Hope this will help you. 

I did not see any infinite loops though.
Thanks

**Comment by mission-peace** [comment]
I meant do you have a smaller example where you get NPE instead of this 63K long string.

**Comment by mfazeen** [comment]
Sorry, I did not get any NPE with smaller strings that I tried with. If I come across one I will let you know.

**Comment by walaanagyis** [comment]
is there any c# version of this code??

**Comment by mission-peace** [comment]
fixed some bugs. Probably that will fix this issue.
