### ISSUE TITLE
Why not return all the possible Strings in word break problem

### ISSUE THREAD

**Issue by puneetsl** [mission-peace/interview#24]
Regarding: `interview/src/com/interview/dynamic/BreakMultipleWordsWithNoSpaceIntoSpace.java`

I think the solution you wanted to write should provide all the possible `Strings`.

BTW, I really like your Youtube channel, it would really awesome if you could create a video for this change request as well.

**Comment by mission-peace** [comment]
i have updated the code for now to generate all possible combinations. I will consider later on if I want to make video on this or not.
