### ISSUE TITLE
Unit Tests for improved test coverage

### ISSUE THREAD

**Issue by mfarid** [mission-peace/interview#32]
I would like know if it will be helpful if I contribute some unit tests. 

Thank you
Farid

**Comment by mission-peace** [comment]
Sure. That would help. Which problem you want to add unit tests for?

**Comment by mfarid** [comment]
Thanks, I have not identified any specific problem.

I am in the process of identifying the potential open source  projects which are looking for contribution in unit tests coverage. My organisation DevFactory - is sponsoring me to improve unit test coverage in open source projects.

I will share this with our team and will start by raising a small Pull Request.

**Comment by mission-peace** [comment]
Closing this issue.
