### ISSUE TITLE
Contribution to some algorithm implementations in Python Language

### ISSUE THREAD

**Issue by ahenteti** [mission-peace/interview#35]
At first, I would like to thank you for this project, it helped me a lot.
And I'd like to know if it would be helpful if I contribute to some algorithm implementations in Python Language. 
Thank you
Ahmed Henteti

**Comment by bmoussa** [comment]
Hi @ahenteti
It’s a good idea

**Comment by mission-peace** [comment]
Please feel free to send PR in python as long as code logic is similar to Java.
