### ISSUE TITLE
Suffix tree: validation fails

### ISSUE THREAD

**Issue by ercoppa** [mission-peace/interview#4]
Hi,

I have tested your implementation of the Suffix Tree data structure. The validation step fails when using:

    SuffixTree st = new SuffixTree("GGACTACGATTTGTGTTCATATTAGTTCA".toCharArray());
    st.build();
    System.out.println(st.validate());

And the output is:

    Mismatch found $ T
    Failed validation
    false

Do you know where is the problem?

Emilio

**Comment by mission-peace** [comment]
Let me look at it. Thanks for brining it up. 


     On Tuesday, July 14, 2015 7:48 AM, ercoppa <notifications@github.com> wrote:
   

 Hi,I have tested your implementation of the Suffix Tree data structure. The validation step fails when using:
 SuffixTree st = new SuffixTree("GGACTACGATTTGTGTTCATATTAGTTCA".toCharArray());
 st.build();
 System.out.println(st.validate());
And the output is:
 Mismatch found $ T
 Failed validation
 false
Do you know where is the problem?Emilio—

**Comment by mission-peace** [comment]
fixed the bug. 
https://github.com/mission-peace/interview/commit/02f0b6fc92143cb2dd61cf748efd629e10a7bdcb
Closing

**Comment by mission-peace** [comment]
Fixed some bugs.
https://github.com/mission-peace/interview/commit/02f0b6fc92143cb2dd61cf748efd629e10a7bdcb
Probably this will fix this bug as well.
