### ISSUE TITLE
AVLTree isn't working as expected 

### ISSUE THREAD

**Issue by guptasujeet** [mission-peace/interview#5]
Just try insert in the order 1, 3, 2 and notice that tree isn't balancing itself

**Comment by mission-peace** [comment]
I tried. To me it looks correct.  Why do you think AVL tree is not balancing? 
1 is root then 3 goes to right. Then 2 goes to 3s left. So now tree is unbalanced from 1s perspective so we do right rotation at 3 to make 2 root and 3 as its right child and then we do left rotation at 1 to make 2 as root and 1 as left and 3 as right child.

**Comment by guptasujeet** [comment]
When I run with 3 nodes it doesn't balances 

For example insert 1, 2, 3 

```code
   1       
    \   
     \  
     2   
      \ 
      3 
```

When 1, 2, 3, 4 is inserted then output tree is like this (which balances it self)

```code 
   2       
  / \   
 /   \  
 1   3   
      \ 
      4 
```

**Comment by mission-peace** [comment]
it never like below
 1
   2
     3

it is   2    if you look at preorder and inorder traversal.
      1   3

**Comment by mission-peace** [comment]
Preorder traversal of tree is 2 1 3. Which means 2 is root 1 is left and 3 is right child. Look at the preorder traversal in the output.

It is never 1 2 3 as you are saying.

**Comment by guptasujeet** [comment]
Sorry , my bad. 

The issue occurred because of some of my changes in the code. 

Thanks for the prompt reply.
