### ISSUE TITLE
BinaryTree Implementation

### ISSUE THREAD

**Issue by nitinmahesh** [mission-peace/interview#73]
Hi,
I was going through the implementation of the BinaryTree in tree source repository. I could not see how this logic(below) make this as Binary Tree?
```
if(head.data < data){
                head = head.right;
            }else{
                head = head.left;
            }
```

Isn't this logic is related to BST?

Thanks
Nitin

**Comment by mission-peace** [comment]
yes. This makes it binary search tree. I ll change the name of the class. Thanks for reporting it.
