### ISSUE TITLE
Size is not required & not used anywhere in the class.

### ISSUE THREAD

**Issue by mayankmukherjee21** [mission-peace/interview#95]
Hi ,
The "size" property is not required & not used anywhere in the AVLTree.java class.

Not sure why it is calculated/kept in the class then. Please advise.

https://github.com/mission-peace/interview/blob/master/src/com/interview/tree/AVLTree.java

Thanks,
Mayank

**Comment by mission-peace** [comment]
its a generic Node class where size is actually used by other classes which is why I m maintaining it
